# This is a basic workflow to help you get started with Actions

name: CI

on:
  # pull_request:
  workflow_dispatch:
    inputs:
      nightly:
        required: true
        type: boolean

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          gh workflow run blank2.yml --ref task00 -f nightly=true
