# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      nightly:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.action_ref }}
