
name: CI

on:
  pull_request:
  push:


jobs:
  build:
    name: auau
    runs-on: ubuntu-latest

    steps:
      - run: |
        echo $GITHUB_REF	
        echo ${{ github.ref }}	
        echo ${{ github.ref_name }}	
        echo ${{ github.head_ref }}
        echo ${{ github.base_ref }}
